# Generated by Django 4.2 on 2023-04-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0003_alter_empmodel_address_alter_empmodel_addressdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmodel',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
