# Generated by Django 4.2 on 2023-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0004_alter_empmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
