# Generated by Django 4.2 on 2023-04-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0006_remove_empmodel_address_remove_empmodel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
